# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='credenciales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('puerto', models.CharField(max_length=5)),
                ('cat_tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cat_tecnologias')),
            ],
        ),
        migrations.CreateModel(
            name='documento_archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cat_documentos')),
            ],
        ),
        migrations.CreateModel(
            name='equipo_ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_especialidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cat_especialidad')),
                ('cat_personas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cat_personas')),
            ],
        ),
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('git', models.CharField(max_length=50)),
                ('tipouso', models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO')], max_length=20, verbose_name='Tipo de uso')),
                ('dependencia_id', models.IntegerField()),
                ('cat_estatus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cat_estatus')),
                ('contacto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cat_personas')),
                ('credencial_id', models.ManyToManyField(blank=True, to='docuamentacion.credenciales')),
            ],
        ),
        migrations.CreateModel(
            name='ficha_cat_tecnologias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('cat_tecnologias_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cat_tecnologias')),
                ('ficha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docuamentacion.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='logtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('nametabla', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('tipomovimiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='equipo_ficha',
            name='ficha_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docuamentacion.ficha'),
        ),
        migrations.AddField(
            model_name='documento_archivo',
            name='ficha_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docuamentacion.ficha'),
        ),
    ]
