# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_personas',
            name='puc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
